// client/src/components/AppLayout.tsx
import React from 'react';
import { Layout, Tabs, Button, Typography, Space, Avatar } from 'antd';
import {
  LogoutOutlined,
  PlusOutlined,
  UserOutlined,
  CompassOutlined,
  SunOutlined,
  MoonOutlined,
} from '@ant-design/icons';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import { useThemeStore } from '../store/themeStore';
import { NomadLogoIcon, MyTripIcon } from './NomadIcons';
import SkateboardTabBar from './SkateboardTabBar';
import SearchBar from './SearchBar';

const { Header, Content } = Layout;
const { Text } = Typography;

interface AppLayoutProps {
  children?: React.ReactNode;
}

export default function AppLayout({ children }: AppLayoutProps) {
  const { user, logout } = useAuthStore();
  const { mode, toggleTheme } = useThemeStore();
  const navigate = useNavigate();
  const location = useLocation();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const activeKey = (() => {
    if (location.pathname === '/') return '/';
    if (location.pathname.startsWith('/explore')) return '/explore';
    return '';
  })();

  const tabItems = [
    {
      key: '/',
      label: (
        <span>
          <MyTripIcon size={14} /> 我的旅程
        </span>
      ),
    },
    {
      key: '/explore',
      label: (
        <span>
          <CompassOutlined /> 微游记
        </span>
      ),
    },
  ];

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Header
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: '#001529',
          padding: '0 24px',
        }}
      >
        <Space>
          <NomadLogoIcon size={22} color="#fff" />
          <Text strong style={{ color: '#fff', fontSize: 18 }}>
            NomadNotes
          </Text>
        </Space>

        <Space size="middle">
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={() => navigate('/trip/new')}
          >
            新建旅程
          </Button>
          <Space
            style={{ cursor: 'pointer' }}
            onClick={() => navigate('/profile')}
          >
            {user?.avatarUrl ? (
              <Avatar src={user.avatarUrl} />
            ) : (
              <Avatar style={{ backgroundColor: '#1890ff' }} icon={<UserOutlined />}>
                {user?.username?.charAt(0).toUpperCase()}
              </Avatar>
            )}
            <Text style={{ color: '#fff' }}>{user?.username}</Text>
          </Space>
          <Button
            type="text"
            icon={mode === 'dark' ? <SunOutlined /> : <MoonOutlined />}
            onClick={toggleTheme}
            style={{ color: '#fff' }}
          />
          <Button
            type="text"
            icon={<LogoutOutlined />}
            onClick={handleLogout}
            style={{ color: '#fff' }}
          >
            退出
          </Button>
        </Space>
      </Header>

      <Tabs
        activeKey={activeKey}
        onChange={(key) => navigate(key)}
        renderTabBar={() => (
          <div style={{ padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <SkateboardTabBar
              activeKey={activeKey}
              onChange={(key: string) => navigate(key)}
              items={tabItems}
            />
            <SearchBar style={{ flexShrink: 0 }} />
          </div>
        )}
        items={tabItems}
        style={{ marginBottom: 0 }}
      />

      <Content
        style={{
          padding: 24,
          maxWidth: 1200,
          margin: '0 auto',
          width: '100%',
        }}
      >
        {children || <Outlet />}
      </Content>
    </Layout>
  );
}

// client-Vue3/src/components/AppLayout.vue
<template>
	<el-container style="min-height: 100vh">
		<!-- 顶部导航栏 -->
		<el-header style="display: flex; align-items: center; justify-content: space-between; background: #001529; padding: 0 24px">
			<el-space>
				<NomadLogoIcon
					:size="22"
					color="#fff"
				/>
				<span style="color: #fff; font-size: 18px; font-weight: 600"> NomadNotes </span>
			</el-space>

			<el-space :size="16">
				<el-button
					type="primary"
					@click="router.push('/trip/new')"
				>
					<el-icon><Plus /></el-icon>新建旅程
				</el-button>

				<el-space
					:size="8"
					style="cursor: pointer"
					@click="router.push('/profile')"
				>
					<el-avatar
						v-if="authStore.user?.avatarUrl"
						:src="authStore.user.avatarUrl"
						:size="32"
					/>
					<el-avatar
						v-else
						:size="32"
					>
						{{ authStore.user?.username?.charAt(0).toUpperCase() }}
					</el-avatar>
					<span style="color: #fff">{{ authStore.user?.username }}</span>
				</el-space>

				<el-button
					text
					style="color: #fff"
					@click="themeStore.toggleTheme()"
				>
					<el-icon>
						<Sunny v-if="themeStore.mode === 'dark'" />
						<Moon v-else />
					</el-icon>
				</el-button>

				<el-button
					text
					style="color: #fff"
					@click="handleLogout"
				>
					<el-icon><SwitchButton /></el-icon>退出
				</el-button>
			</el-space>
		</el-header>

		<!-- Tab 导航栏 -->
		<div style="padding: 0 24px; display: flex; align-items: center; justify-content: space-between">
			<SkateboardTabBar
				:active-key="activeKey"
				:items="tabItems"
				@update:active-key="(key: string) => router.push(key)"
			>
				<template
					v-for="tab in tabItems"
					:key="tab.key"
					#[`label-${tab.key}`]
				>
					<span>
						<MyTripIcon
							v-if="tab.key === '/'"
							:size="14"
						/>
						<el-icon v-if="tab.key === '/explore'"><Compass /></el-icon>
						{{ tab.label }}
					</span>
				</template>
			</SkateboardTabBar>
			<SearchBar />
		</div>

		<!-- 内容区域 -->
		<el-main style="padding: 24px; max-width: 1200px; margin: 0 auto; width: 100%">
			<slot />
		</el-main>
	</el-container>
</template>

<script setup lang="ts">
	import { computed } from "vue";
	import { useRouter, useRoute } from "vue-router";
	import { Plus, Sunny, Moon, SwitchButton, Compass } from "@element-plus/icons-vue";
	import { useAuthStore } from "../stores/authStore";
	import { useThemeStore } from "../stores/themeStore";
	import NomadLogoIcon from "./NomadLogoIcon.vue";
	import MyTripIcon from "./MyTripIcon.vue";
	import SkateboardTabBar from "./SkateboardTabBar.vue";
	import SearchBar from "./SearchBar.vue";

	const authStore = useAuthStore();
	const themeStore = useThemeStore();
	const router = useRouter();
	const route = useRoute();

	const activeKey = computed(() => {
		if (route.path === "/") return "/";
		if (route.path.startsWith("/explore")) return "/explore";
		return "";
	});

	const tabItems = [
		{ key: "/", label: "我的旅程" },
		{ key: "/explore", label: "微游记" },
	];

	function handleLogout() {
		authStore.logout();
		router.push("/login");
	}
</script>
