// client/src/components/CurrencySwitcher.tsx
import React, { useEffect, useState, useCallback } from "react";
import { Select, Space } from "antd";
import { DollarOutlined } from "@ant-design/icons";
import { getCurrencyRates } from "../api/currency";
import { useCurrencyStore } from "../store/currencyStore";
import type { CurrencyInfo } from "../types";

/**
 * 货币切换组件
 * 提供货币选择和自动转换显示
 */
const CurrencySwitcher: React.FC<{ style?: React.CSSProperties; size?: "small" | "middle" | "large" }> = ({
	style,
	size = "small",
}) => {
	const { currency, setCurrency, setRates, loading, setLoading } = useCurrencyStore();
	const [currencies, setCurrencies] = useState<CurrencyInfo[]>([]);

	// 加载汇率数据
	const loadRates = useCallback(async () => {
		setLoading(true);
		try {
			const data = await getCurrencyRates();
			setRates(data.rates);
			setCurrencies(data.currencies);
		} catch (error: unknown) {
			console.error("获取汇率失败:", error);
		} finally {
			setLoading(false);
		}
	}, [setLoading, setRates]);

	useEffect(() => {
		loadRates();
	}, [loadRates]);

	// 构建下拉选项
	const options = currencies.map((c) => ({
		value: c.code,
		label: (
			<span>
				{c.symbol} {c.code} - {c.name}
			</span>
		),
	}));

	return (
		<Space size={4} style={style}>
			<DollarOutlined style={{ color: "#52c41a", fontSize: size === "large" ? 18 : 14 }} />
			<Select
				value={currency}
				onChange={(val) => setCurrency(val)}
				options={options}
				loading={loading}
				size={size}
				style={{ minWidth: 130 }}
				popupMatchSelectWidth={false}
				variant="borderless"
			/>
		</Space>
	);
};

export default CurrencySwitcher;

// client-Vue3/src/components/CurrencySwitcher.vue
<template>
	<el-space
		:size="4"
		:style="style"
	>
		<el-icon
			style="color: #52c41a"
			:size="size === 'large' ? 18 : 14"
		>
			<Money />
		</el-icon>
		<el-select
			:model-value="currencyStore.currency"
			@update:model-value="currencyStore.setCurrency"
			:loading="currencyStore.loading"
			:size="size"
			style="min-width: 130px"
			:teleported="false"
		>
			<el-option
				v-for="c in currencies"
				:key="c.code"
				:value="c.code"
				:label="`${c.symbol} ${c.code} - ${c.name}`"
			/>
		</el-select>
	</el-space>
</template>

<script setup lang="ts">
	import { ref, onMounted } from "vue";
	import { Money } from "@element-plus/icons-vue";
	import { getCurrencyRates } from "../api/currency";
	import { useCurrencyStore } from "../stores/currencyStore";
	import type { CurrencyInfo } from "../types";

	const props = withDefaults(
		defineProps<{
			size?: "small" | "default" | "large";
			style?: Record<string, string | number>;
		}>(),
		{
			size: "small",
		},
	);

	const currencyStore = useCurrencyStore();
	const currencies = ref<CurrencyInfo[]>([]);

	async function loadRates() {
		currencyStore.setLoading(true);
		try {
			const data = await getCurrencyRates();
			currencyStore.setRates(data.rates);
			currencies.value = data.currencies;
		} catch (error: unknown) {
			console.error("获取汇率失败:", error);
		} finally {
			currencyStore.setLoading(false);
		}
	}

	onMounted(() => {
		loadRates();
	});
</script>
