// client-Vue3/src/pages/PublicTripDetailPage.vue
<template>
	<div>
		<!-- 面包屑导航 -->
		<el-breadcrumb style="margin-bottom: 16px">
			<el-breadcrumb-item :to="{ path: '/explore' }">微游记</el-breadcrumb-item>
			<el-breadcrumb-item>{{ tripData?.title || "" }}</el-breadcrumb-item>
		</el-breadcrumb>

		<!-- 标题区域 -->
		<div style="margin-bottom: 24px">
			<h3 style="margin-bottom: 4px; font-size: 20px; font-weight: 600">{{ tripData?.title }}</h3>
			<el-space>
				<el-tag type="primary">{{ tripData?.destination }}</el-tag>
				<span style="color: rgba(0, 0, 0, 0.45); font-size: 14px">
					<el-icon style="margin-right: 4px"><Calendar /></el-icon>
					{{ formatDateTime(tripData?.startDate) }} ~ {{ formatDateTime(tripData?.endDate) }}
				</span>
			</el-space>
		</div>

		<el-skeleton
			v-if="loading"
			:rows="8"
			animated
		/>

		<template v-if="!loading && tripData">
			<!-- 自定义 TabBar -->
			<SkateboardTabBar
				:active-key="activeTab"
				:items="tabItems"
				@update:active-key="(key: string) => setActiveTab(key)"
			/>

			<!-- Tabs 内容区（隐藏 el-tabs 自带 header） -->
			<el-tabs
				v-model="activeTab"
				class="hidden-tabs-header"
			>
				<!-- 概览 Tab -->
				<el-tab-pane name="overview">
					<!-- 封面图 -->
					<div
						v-if="tripData.coverImage"
						style="margin-bottom: 24px"
					>
						<el-image
							:src="tripData.coverImage"
							style="width: 100%; max-height: 500px; object-fit: cover; border-radius: 12px; cursor: pointer"
							fit="cover"
							:preview-src-list="[tripData.coverImage]"
							:preview-teleported="true"
						/>
					</div>

					<el-descriptions
						bordered
						:column="2"
					>
						<el-descriptions-item label="目的地">
							{{ tripData.destination }}
						</el-descriptions-item>
						<el-descriptions-item label="作者">
							<el-space>
								<el-avatar
									:size="22"
									:src="tripData.User?.avatarUrl ?? undefined"
									:icon="User"
								/>
								<span>{{ tripData.User?.username || "匿名用户" }}</span>
							</el-space>
						</el-descriptions-item>
						<el-descriptions-item label="开始日期">
							{{ formatDateTime(tripData.startDate) }}
						</el-descriptions-item>
						<el-descriptions-item label="结束日期">
							{{ tripData.endDate ? formatDateTime(tripData.endDate) : "-" }}
						</el-descriptions-item>
						<el-descriptions-item label="状态">
							<el-tag :type="tripData.isEnded ? 'primary' : 'success'">
								{{ tripData.isEnded ? "已结束" : "进行中" }}
							</el-tag>
						</el-descriptions-item>
						<el-descriptions-item label="消费笔数"> {{ tripData.expenseCount || 0 }} 笔 </el-descriptions-item>
						<el-descriptions-item label="游记篇数"> {{ tripData.noteCount || 0 }} 篇 </el-descriptions-item>
						<el-descriptions-item label="创建时间">
							{{ formatDateTime(tripData.createdAt) }}
						</el-descriptions-item>
					</el-descriptions>
				</el-tab-pane>

				<!-- 账单 Tab -->
				<el-tab-pane
					v-if="expenses.length > 0"
					name="expenses"
				>
					<el-table
						:data="expenses"
						row-key="id"
						style="width: 100%"
						:pagination="{ pageSize: 10, size: 'small' }"
						size="default"
					>
						<el-table-column
							prop="expenseDate"
							label="日期"
							width="180"
							align="center"
						>
							<template #default="{ row }">
								{{ formatDateTime(row.expenseDate) }}
							</template>
						</el-table-column>
						<el-table-column
							prop="category"
							label="分类"
							width="100"
							align="center"
						>
							<template #default="{ row }">
								<el-tag>
									{{ row.category }}
								</el-tag>
							</template>
						</el-table-column>
						<el-table-column
							prop="amount"
							label="金额"
							width="120"
							align="center"
						>
							<template #default="{ row }">
								<span style="color: #ff4d4f; font-weight: 700"> ¥{{ Number(row.amount).toFixed(2) }} </span>
							</template>
						</el-table-column>
						<el-table-column
							prop="note"
							label="备注"
							min-width="150"
							align="center"
						>
							<template #default="{ row }">
								{{ row.note || "-" }}
							</template>
						</el-table-column>
					</el-table>
				</el-tab-pane>

				<!-- 游记 Tab -->
				<el-tab-pane
					v-if="notes.length > 0"
					name="notes"
				>
					<el-timeline>
						<el-timeline-item
							v-for="note in notes"
							:key="note.id"
							:timestamp="formatDateTime(note.noteDate)"
							placement="top"
						>
							<el-card
								shadow="hover"
								size="small"
								style="margin-bottom: 12px"
							>
								<p style="white-space: pre-wrap; margin-bottom: 12px; line-height: 1.8; font-size: 15px">
									{{ note.content }}
								</p>
								<div v-if="note.images && note.images.length > 0">
									<el-space
										wrap
										:size="[12, 12]"
									>
										<el-image
											v-for="(img, i) in note.images"
											:key="i"
											:src="img"
											style="width: 200px; height: 200px; object-fit: cover; border-radius: 8px; cursor: pointer; border: 1px solid #f0f0f0"
											fit="cover"
											:preview-src-list="note.images"
											:initial-index="i"
											preview-teleported
										/>
									</el-space>
								</div>
							</el-card>
						</el-timeline-item>
					</el-timeline>
				</el-tab-pane>

				<!-- 统计 Tab -->
				<el-tab-pane
					v-if="expenses.length > 0"
					name="stats"
				>
					<!-- 统计卡片 -->
					<el-row
						:gutter="16"
						style="margin-bottom: 24px"
					>
						<el-col
							:xs="24"
							:sm="12"
							:lg="6"
						>
							<el-card shadow="hover">
								<el-statistic
									title="总支出"
									:value="statsSummary.total"
									:precision="2"
									prefix="¥"
									value-style="color: #cf1322"
								/>
							</el-card>
						</el-col>
						<el-col
							:xs="24"
							:sm="12"
							:lg="6"
						>
							<el-card shadow="hover">
								<el-statistic
									title="日均支出"
									:value="statsSummary.avgPerDay"
									:precision="2"
									prefix="¥"
									value-style="color: #1890ff"
								/>
							</el-card>
						</el-col>
						<el-col
							:xs="24"
							:sm="12"
							:lg="6"
						>
							<el-card shadow="hover">
								<el-statistic
									title="消费笔数"
									:value="statsSummary.count"
									suffix="笔"
									value-style="color: #722ed1"
								/>
							</el-card>
						</el-col>
						<el-col
							:xs="24"
							:sm="12"
							:lg="6"
						>
							<el-card shadow="hover">
								<div style="text-align: center">
									<div style="font-size: 14px; color: rgba(0, 0, 0, 0.45); margin-bottom: 4px">最高消费类别</div>
									<div style="font-size: 16px; font-weight: 600; color: #fa8c16">
										{{ statsSummary.maxCategory || "-" }}
									</div>
								</div>
							</el-card>
						</el-col>
					</el-row>

					<!-- 分类图表 -->
					<el-row
						v-if="categoryStats.categories.length > 0"
						:gutter="16"
					>
						<el-col
							:xs="24"
							:lg="12"
						>
							<el-card
								shadow="hover"
								title="消费分类分布"
								style="margin-bottom: 16px"
							>
								<div style="width: 100%; height: 350px">
									<v-chart
										:option="pieChartOption"
										autoresize
									/>
								</div>
							</el-card>
						</el-col>
						<el-col
							:xs="24"
							:lg="12"
						>
							<el-card
								shadow="hover"
								title="每日消费趋势"
								style="margin-bottom: 16px"
							>
								<div
									v-if="dailyExpenseData.length > 0"
									style="width: 100%; height: 350px"
								>
									<v-chart
										:option="barChartOption"
										autoresize
									/>
								</div>
								<el-empty
									v-else
									description="暂无日消费数据"
								/>
							</el-card>
						</el-col>
					</el-row>

					<!-- 分类明细表 -->
					<el-card
						v-if="categoryStats.categories.length > 0"
						shadow="hover"
						size="small"
						style="margin-top: 16px"
					>
						<template #header>
							<span>分类明细</span>
						</template>
						<el-table
							:data="categoryStats.categories"
							row-key="category"
							style="width: 100%"
						>
							<el-table-column
								prop="category"
								label="分类"
							>
								<template #default="{ row }">
									<el-tag>{{ row.category }}</el-tag>
								</template>
							</el-table-column>
							<el-table-column
								prop="count"
								label="笔数"
								align="right"
							/>
							<el-table-column
								prop="total"
								label="金额"
								align="right"
							>
								<template #default="{ row }">
									<span style="color: #ff4d4f; font-weight: 700"> ¥{{ row.total.toFixed(2) }} </span>
								</template>
							</el-table-column>
							<el-table-column
								label="占比"
								align="right"
							>
								<template #default="{ row }">
									{{ categoryStats.total > 0 ? ((row.total / categoryStats.total) * 100).toFixed(1) + "%" : "0.0%" }}
								</template>
							</el-table-column>
						</el-table>
					</el-card>
				</el-tab-pane>
			</el-tabs>
		</template>
	</div>
</template>

<script setup lang="ts">
	import { ref, computed, onMounted } from "vue";
	import { useRoute, useRouter } from "vue-router";
	import { User, Calendar } from "@element-plus/icons-vue";
	import { ElMessage } from "element-plus";
	import { getPublicTripById } from "../api/trips";
	import SkateboardTabBar from "../components/SkateboardTabBar.vue";
	import VChart from "vue-echarts";
	import { use } from "echarts/core";
	import { PieChart } from "echarts/charts";
	import { BarChart } from "echarts/charts";
	import { TooltipComponent, LegendComponent, GridComponent } from "echarts/components";
	import { CanvasRenderer } from "echarts/renderers";
	import type { Trip, Expense, Note } from "../types";
	import dayjs from "dayjs";

	use([PieChart, BarChart, TooltipComponent, LegendComponent, GridComponent, CanvasRenderer]);

	const route = useRoute();
	const router = useRouter();

	const loading = ref(true);
	const activeTab = ref("overview");
	const tripData = ref<(Trip & { expenses?: Expense[]; notes?: Note[] }) | null>(null);

	const COLORS = ["#667eea", "#764ba2", "#f093fb", "#f5576c", "#4facfe", "#00f2fe", "#43e97b", "#fa709a", "#a18cd1", "#fccb90"];

	const expenses = computed<Expense[]>(() => tripData.value?.expenses || []);
	const notes = computed<Note[]>(() => tripData.value?.notes || []);

	// Tab 配置项
	const tabItems = computed(() => {
		const items: { key: string; label: string }[] = [{ key: "overview", label: "概览" }];
		if (expenses.value.length > 0) {
			items.push({
				key: "expenses",
				label: `账单 (${expenses.value.length})`,
			});
		}
		if (notes.value.length > 0) {
			items.push({ key: "notes", label: `游记 (${notes.value.length})` });
		}
		if (expenses.value.length > 0) {
			items.push({ key: "stats", label: "统计" });
		}
		return items;
	});

	// 每日消费数据
	const dailyExpenseData = computed(() => {
		const map: Record<string, number> = {};
		for (const e of expenses.value) {
			const date = dayjs(e.expenseDate).format("YYYY-MM-DD");
			map[date] = (map[date] || 0) + Number(e.amount);
		}
		return Object.entries(map)
			.map(([date, amount]) => ({
				date,
				amount: Math.round(amount * 100) / 100,
			}))
			.sort((a, b) => a.date.localeCompare(b.date));
	});

	// 分类统计
	const categoryStats = computed(() => {
		const map: Record<string, { total: number; count: number }> = {};
		let total = 0;
		for (const e of expenses.value) {
			const amount = Number(e.amount);
			total += amount;
			if (!map[e.category]) {
				map[e.category] = { total: 0, count: 0 };
			}
			map[e.category].total += amount;
			map[e.category].count += 1;
		}
		const categories = Object.entries(map).map(([cat, data]) => ({
			category: cat,
			total: Math.round(data.total * 100) / 100,
			count: data.count,
		}));
		categories.sort((a, b) => b.total - a.total);
		return { total: Math.round(total * 100) / 100, categories };
	});

	// 统计摘要
	const statsSummary = computed(() => {
		const total = expenses.value.reduce((sum, e) => sum + Number(e.amount), 0);
		if (expenses.value.length === 0) {
			return { total: 0, avgPerDay: 0, maxCategory: null, count: 0 };
		}

		const catTotals: Record<string, number> = {};
		const dates = new Set<string>();
		for (const e of expenses.value) {
			catTotals[e.category] = (catTotals[e.category] || 0) + Number(e.amount);
			dates.add(dayjs(e.expenseDate).format("YYYY-MM-DD"));
		}

		let maxCat = "";
		let maxAmt = 0;
		for (const [cat, amt] of Object.entries(catTotals)) {
			if (amt > maxAmt) {
				maxAmt = amt;
				maxCat = cat;
			}
		}

		return {
			total: Math.round(total * 100) / 100,
			avgPerDay: dates.size > 0 ? Math.round((total / dates.size) * 100) / 100 : 0,
			maxCategory: maxCat ? `${maxCat} (¥${Math.round(maxAmt * 100) / 100})` : null,
			count: expenses.value.length,
		};
	});

	// 饼图配置
	const pieChartOption = computed(() => {
		if (categoryStats.value.categories.length === 0) return {};
		return {
			tooltip: {
				trigger: "item",
				formatter: (params: { data: { value: number } }) => `¥${params.data.value.toFixed(2)}`,
			},
			legend: { bottom: 0 },
			series: [
				{
					name: "消费分类",
					type: "pie",
					radius: ["40%", "70%"],
					center: ["50%", "45%"],
					data: categoryStats.value.categories.map((c) => ({
						name: c.category,
						value: c.total,
					})),
					color: COLORS,
					label: {
						formatter: (params: { name: string; value: number }) => `${params.name} ¥${params.value.toFixed(2)}`,
					},
				},
			],
		};
	});

	// 柱状图配置
	const barChartOption = computed(() => {
		if (dailyExpenseData.value.length === 0) return {};
		return {
			tooltip: {
				trigger: "axis",
				formatter: (params: { value: number }[]) => `¥${params[0].value.toFixed(2)}`,
			},
			grid: {
				left: "3%",
				right: "4%",
				bottom: "3%",
				containLabel: true,
			},
			xAxis: {
				type: "category",
				data: dailyExpenseData.value.map((d) => d.date),
			},
			yAxis: { type: "value" },
			series: [
				{
					data: dailyExpenseData.value.map((d) => d.amount),
					type: "bar",
					itemStyle: {
						color: "#1890ff",
						borderRadius: [4, 4, 0, 0],
					},
				},
			],
		};
	});

	function formatDateTime(dateStr: string | null | undefined) {
		return dateStr ? dayjs(dateStr).format("YYYY-MM-DD HH:mm:ss") : "";
	}

	function setActiveTab(key: string) {
		activeTab.value = key;
	}

	onMounted(async () => {
		const tripId = route.params.id as string;
		try {
			tripData.value = (await getPublicTripById(tripId)) as Trip & {
				expenses?: Expense[];
				notes?: Note[];
			};
		} catch {
			ElMessage.error("该游记不存在或已设为私密");
			router.replace("/explore");
		} finally {
			loading.value = false;
		}
	});
</script>

<style scoped>
	/* 隐藏 el-tabs 自带的 tab header，使用自定义 SkateboardTabBar 替代 */
	.hidden-tabs-header :deep(.el-tabs__header) {
		display: none;
	}
</style>

// client/src/pages/PublicTripDetailPage.tsx
import React, { useMemo, useState } from 'react';
import {
  Tabs,
  Typography,
  Spin,
  message,
  Descriptions,
  Tag,
  Empty,
  Timeline,
  Card,
  Breadcrumb,
  Avatar,
  Row,
  Col,
  Statistic,
  Table,
  Space,
  Image,
} from 'antd';
import {
  ArrowLeftOutlined,
  PieChartOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  UserOutlined,
  CalendarOutlined,
  FileTextOutlined,
  ClockCircleOutlined,
} from '@ant-design/icons';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getPublicTripById } from '../api/trips';
import { useAuthStore } from '../store/authStore';
import { TripDetailSkeleton } from '../components/Skeletons';
import SkateboardTabBar from '../components/SkateboardTabBar';
import type { Trip, Expense, Note } from '../types';
import dayjs from 'dayjs';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
} from 'recharts';

const { Title, Text, Paragraph } = Typography;

const COLORS = ['#667eea', '#764ba2', '#f093fb', '#f5576c', '#4facfe', '#00f2fe', '#43e97b', '#fa709a', '#a18cd1', '#fccb90'];

const CATEGORY_COLORS: Record<string, string> = {
  '餐饮': '#f5576c',
  '交通': '#4facfe',
  '住宿': '#667eea',
  '购物': '#f093fb',
  '娱乐': '#43e97b',
  '景点': '#fa709a',
  '其他': '#a18cd1',
};

export default function PublicTripDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const currentUserId = useAuthStore((s) => s.user?.id);
  const [activeTab, setActiveTab] = useState('overview');

  const { data: trip, isLoading, isError } = useQuery({
    queryKey: ['publicTrip', id],
    queryFn: () => getPublicTripById(id!),
    enabled: !!id,
    staleTime: 5 * 60 * 1000,
  });

  const tripData = trip as Trip & { expenses?: Expense[]; notes?: Note[] } | undefined;
  const expenses = (tripData?.expenses as Expense[]) || [];
  const notes = (tripData?.notes as Note[]) || [];

  const dailyExpenseData = useMemo(() => {
    const map: Record<string, number> = {};
    for (const e of expenses) {
      const date = dayjs(e.expenseDate).format('YYYY-MM-DD');
      map[date] = (map[date] || 0) + Number(e.amount);
    }
    return Object.entries(map)
      .map(([date, amount]) => ({ date, amount: Math.round(amount * 100) / 100 }))
      .sort((a, b) => a.date.localeCompare(b.date));
  }, [expenses]);

  const categoryStats = useMemo(() => {
    const categoryMap: Record<string, { total: number; count: number }> = {};
    let totalAmount = 0;
    for (const e of expenses) {
      const amount = Number(e.amount);
      totalAmount += amount;
      if (!categoryMap[e.category]) {
        categoryMap[e.category] = { total: 0, count: 0 };
      }
      categoryMap[e.category].total += amount;
      categoryMap[e.category].count += 1;
    }
    const categories = Object.entries(categoryMap).map(([category, data]) => ({
      category,
      total: Math.round(data.total * 100) / 100,
      count: data.count,
    }));
    categories.sort((a, b) => b.total - a.total);
    return { total: Math.round(totalAmount * 100) / 100, categories };
  }, [expenses]);

  const statsSummary = useMemo(() => {
    const total = expenses.reduce((sum, e) => sum + Number(e.amount), 0);
    if (expenses.length === 0) return { total: 0, avgPerDay: 0, maxCategory: null, count: 0 };

    const categoryTotals: Record<string, number> = {};
    const dates = new Set<string>();
    for (const e of expenses) {
      categoryTotals[e.category] = (categoryTotals[e.category] || 0) + Number(e.amount);
      dates.add(dayjs(e.expenseDate).format('YYYY-MM-DD'));
    }

    let maxCategory = '';
    let maxAmount = 0;
    for (const [cat, amt] of Object.entries(categoryTotals)) {
      if (amt > maxAmount) {
        maxAmount = amt;
        maxCategory = cat;
      }
    }

    return {
      total: Math.round(total * 100) / 100,
      avgPerDay: dates.size > 0 ? Math.round((total / dates.size) * 100) / 100 : 0,
      maxCategory: maxCategory ? `${maxCategory} (¥${Math.round(maxAmount * 100) / 100})` : null,
      count: expenses.length,
    };
  }, [expenses]);

  if (isLoading) {
    return <TripDetailSkeleton />;
  }

  if (isError || !tripData) {
    message.error('该游记不存在或已设为私密');
    navigate('/explore', { replace: true });
    return null;
  }

  const isOwner = tripData.userId === currentUserId;

  const tabItems = [
    {
      key: 'overview',
      label: (
        <span>
          <EnvironmentOutlined /> 概览
        </span>
      ),
      children: (
        <div>
          {tripData.coverImage && (
            <div style={{ marginBottom: 24 }}>
              <Image
                src={tripData.coverImage}
                alt={tripData.title}
                style={{
                  width: '100%',
                  maxHeight: 500,
                  objectFit: 'cover',
                  borderRadius: 12,
                  cursor: 'pointer',
                }}
                preview={{
                  mask: '查看大图',
                }}
              />
            </div>
          )}

          <Descriptions bordered column={{ xs: 1, sm: 2 }}>
            <Descriptions.Item label="目的地">{tripData.destination}</Descriptions.Item>
            <Descriptions.Item label="作者">
              <Space>
                <Avatar
                  size="small"
                  icon={<UserOutlined />}
                  src={tripData.User?.avatarUrl}
                />
                <Text>{tripData.User?.username || '匿名用户'}</Text>
              </Space>
            </Descriptions.Item>
            <Descriptions.Item label="开始日期">
              {dayjs(tripData.startDate).format('YYYY-MM-DD HH:mm:ss')}
            </Descriptions.Item>
            <Descriptions.Item label="结束日期">
              {dayjs(tripData.endDate).format('YYYY-MM-DD HH:mm:ss')}
            </Descriptions.Item>
            <Descriptions.Item label="状态">
              <Tag color={tripData.isEnded ? 'default' : 'green'}>
                {tripData.isEnded ? '已结束' : '进行中'}
              </Tag>
            </Descriptions.Item>
            <Descriptions.Item label="消费笔数">
              {tripData.expenseCount || 0} 笔
            </Descriptions.Item>
            <Descriptions.Item label="游记篇数">
              {tripData.noteCount || 0} 篇
            </Descriptions.Item>
            <Descriptions.Item label="创建时间">
              {dayjs(tripData.createdAt).format('YYYY-MM-DD HH:mm:ss')}
            </Descriptions.Item>
          </Descriptions>

          {isOwner && (
            <div style={{ marginTop: 16 }}>
              <Link to={`/trip/${tripData.id}`}>
                <Text type="secondary">
                  这是你的旅程，点击进入管理页面
                </Text>
              </Link>
            </div>
          )}
        </div>
      ),
    },
    ...(expenses.length > 0
      ? [
          {
            key: 'expenses',
            label: (
              <span>
                <DollarOutlined /> 账单 ({expenses.length})
              </span>
            ),
            children: (
              <div>
                <Table
                  dataSource={expenses as Expense[]}
                  rowKey="id"
                  pagination={{ pageSize: 10, size: 'small' }}
                  size="middle"
                  columns={[
                    {
                      title: '日期',
                      dataIndex: 'expenseDate',
                      width: 180,
                      align: 'center',
                      render: (d: string) => dayjs(d).format('YYYY-MM-DD HH:mm:ss'),
                    },
                    {
                      title: '分类',
                      dataIndex: 'category',
                      width: 100,
                      align: 'center',
                      render: (c: string) => (
                        <Tag color={CATEGORY_COLORS[c] || '#a18cd1'}>{c}</Tag>
                      ),
                    },
                    {
                      title: '金额',
                      dataIndex: 'amount',
                      width: 120,
                      align: 'center',
                      render: (a: number) => (
                        <Text strong style={{ color: '#ff4d4f' }}>
                          ¥{Number(a).toFixed(2)}
                        </Text>
                      ),
                    },
                    {
                      title: '备注',
                      dataIndex: 'note',
                      align: 'center',
                      ellipsis: true,
                      render: (n: string) => n || '-',
                    },
                  ]}
                />
              </div>
            ),
          },
        ]
      : []),
    ...(notes.length > 0
      ? [
          {
            key: 'notes',
            label: (
              <span>
                <FileTextOutlined /> 游记 ({notes.length})
              </span>
            ),
            children: (
              <div>
                <Timeline
                  mode="left"
                  className="custom-timeline"
                  items={notes.map((note: Note) => ({
                    dot: (
                      <span
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          background: 'transparent',
                        }}
                      >
                        <ClockCircleOutlined
                          style={{ fontSize: 16, color: '#667eea', background: 'transparent' }}
                        />
                      </span>
                    ),
                    children: (
                      <Card
                        size="small"
                        style={{ marginBottom: 12 }}
                        title={
                          <Text type="secondary">
                            {dayjs(note.noteDate).format('YYYY-MM-DD HH:mm:ss')}
                          </Text>
                        }
                      >
                        <Paragraph
                          style={{
                            whiteSpace: 'pre-wrap',
                            marginBottom: 12,
                          }}
                        >
                          {note.content}
                        </Paragraph>
                        {note.images && note.images.length > 0 && (
                          <Space wrap size={[12, 12]}>
                            {note.images.map((img: string, i: number) => (
                              <Image
                                key={i}
                                src={img}
                                width={200}
                                height={200}
                                style={{
                                  objectFit: 'cover',
                                  borderRadius: 8,
                                  cursor: 'pointer',
                                  border: '1px solid #f0f0f0',
                                }}
                                preview={{
                                  mask: '查看大图',
                                }}
                              />
                            ))}
                          </Space>
                        )}
                      </Card>
                    ),
                  }))}
                />
              </div>
            ),
          },
        ]
      : []),
    ...(expenses.length > 0
      ? [
          {
            key: 'stats',
            label: (
              <span>
                <PieChartOutlined /> 统计
              </span>
            ),
            children: (
              <div>
                <Row gutter={16} style={{ marginBottom: 24 }}>
                  <Col xs={24} sm={12} lg={6}>
                    <Card>
                      <Statistic
                        title="总支出"
                        value={statsSummary.total}
                        precision={2}
                        prefix="¥"
                        valueStyle={{ color: '#cf1322' }}
                      />
                    </Card>
                  </Col>
                  <Col xs={24} sm={12} lg={6}>
                    <Card>
                      <Statistic
                        title="日均支出"
                        value={statsSummary.avgPerDay}
                        precision={2}
                        prefix="¥"
                        valueStyle={{ color: '#1890ff' }}
                      />
                    </Card>
                  </Col>
                  <Col xs={24} sm={12} lg={6}>
                    <Card>
                      <Statistic
                        title="消费笔数"
                        value={statsSummary.count}
                        suffix="笔"
                        valueStyle={{ color: '#722ed1' }}
                      />
                    </Card>
                  </Col>
                  <Col xs={24} sm={12} lg={6}>
                    <Card>
                      <Statistic
                        title="最高消费类别"
                        value={statsSummary.maxCategory || '-'}
                        valueStyle={{ fontSize: 16, color: '#fa8c16' }}
                      />
                    </Card>
                  </Col>
                </Row>

                {categoryStats.categories.length > 0 && (
                  <Row gutter={16}>
                    <Col xs={24} lg={12}>
                      <Card title="消费分类分布" style={{ marginBottom: 16 }}>
                        <ResponsiveContainer width="100%" height={350}>
                          <PieChart>
                            <Pie
                              data={categoryStats.categories}
                              dataKey="total"
                              nameKey="category"
                              cx="50%"
                              cy="50%"
                              outerRadius={120}
                              label={({ category, total }: { category: string; total: number }) =>
                                `${category} ¥${total.toFixed(2)}`
                              }
                            >
                              {categoryStats.categories.map((_, index: number) => (
                                <Cell
                                  key={`cell-${index}`}
                                  fill={COLORS[index % COLORS.length]}
                                />
                              ))}
                            </Pie>
                            <Tooltip formatter={(value: number) => `¥${value.toFixed(2)}`} />
                            <Legend />
                          </PieChart>
                        </ResponsiveContainer>
                      </Card>
                    </Col>
                    <Col xs={24} lg={12}>
                      <Card title="每日消费趋势" style={{ marginBottom: 16 }}>
                        {dailyExpenseData.length > 0 ? (
                          <ResponsiveContainer width="100%" height={350}>
                            <BarChart data={dailyExpenseData}>
                              <CartesianGrid strokeDasharray="3 3" />
                              <XAxis dataKey="date" />
                              <YAxis />
                              <Tooltip formatter={(value: number) => `¥${value.toFixed(2)}`} />
                              <Bar dataKey="amount" fill="#1890ff" radius={[4, 4, 0, 0]} />
                            </BarChart>
                          </ResponsiveContainer>
                        ) : (
                          <Empty description="暂无日消费数据" />
                        )}
                      </Card>
                    </Col>
                  </Row>
                )}

                {categoryStats.categories.length > 0 && (
                  <Card title="分类明细" size="small" style={{ marginTop: 16 }}>
                    <Table
                      dataSource={categoryStats.categories}
                      rowKey="category"
                      pagination={false}
                      columns={[
                        {
                          title: '分类',
                          dataIndex: 'category',
                          render: (c: string) => <Tag>{c}</Tag>,
                        },
                        {
                          title: '笔数',
                          dataIndex: 'count',
                          align: 'right',
                        },
                        {
                          title: '金额',
                          dataIndex: 'total',
                          align: 'right',
                          render: (v: number) => (
                            <Text strong style={{ color: '#ff4d4f' }}>
                              ¥{v.toFixed(2)}
                            </Text>
                          ),
                        },
                        {
                          title: '占比',
                          key: 'percent',
                          align: 'right',
                          render: (_: unknown, record: { total: number }) => {
                            const pct = categoryStats.total > 0
                              ? ((record.total / categoryStats.total) * 100).toFixed(1)
                              : '0.0';
                            return `${pct}%`;
                          },
                        },
                      ]}
                    />
                  </Card>
                )}
              </div>
            ),
          },
        ]
      : []),
  ];

  return (
    <div>
      <Breadcrumb
        style={{ marginBottom: 16 }}
        items={[
          {
            title: (
              <Link to="/explore">
                微游记
              </Link>
            ),
          },
          {
            title: tripData.title,
          },
        ]}
      />

      <div style={{ marginBottom: 24 }}>
        <Title level={3} style={{ marginBottom: 4 }}>
          {tripData.title}
        </Title>
        <Space>
          <Tag color="blue">{tripData.destination}</Tag>
          <Text type="secondary">
            <CalendarOutlined /> {dayjs(tripData.startDate).format('YYYY-MM-DD HH:mm:ss')} ~ {dayjs(tripData.endDate).format('YYYY-MM-DD HH:mm:ss')}
          </Text>
        </Space>
      </div>

      <SkateboardTabBar
        activeKey={activeTab}
        onChange={(key: string) => setActiveTab(key)}
        items={tabItems}
      />
      <Tabs
        activeKey={activeTab}
        onChange={(key: string) => setActiveTab(key)}
        tabBarStyle={{ display: 'none' }}
        items={tabItems}
      />
    </div>
  );
}
