// client/src/pages/AdminPage.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import AuditTab from '../components/admin/AuditTab';
import UserTab from '../components/admin/UserTab';
import TripTab from '../components/admin/TripTab';
import OperationLogTab from '../components/admin/OperationLogTab';
import SkateboardTabBar from '../components/SkateboardTabBar';

export default function AdminPage() {
    const { isAdmin } = useAuthStore();
    const navigate = useNavigate();
    const [activeTab, setActiveTab] = useState('audit');

    // 权限检查：仅管理员可访问
    useEffect(() => {
        if (!isAdmin || !isAdmin()) {
            navigate('/', { replace: true });
        }
    }, [isAdmin, navigate]);

    const tabItems = [
        { key: 'audit', label: '内容审核' },
        { key: 'users', label: '用户管理' },
        { key: 'trips', label: '旅程管理' },
        { key: 'logs', label: '操作日志' },
    ];

    // 根据当前激活的标签页渲染对应的子组件
    const renderTabContent = () => {
        switch (activeTab) {
            case 'audit':
                return <AuditTab />;
            case 'users':
                return <UserTab />;
            case 'trips':
                return <TripTab />;
            case 'logs':
                return <OperationLogTab />;
            default:
                return <AuditTab />;
        }
    };

    return (
        <div style={{ maxWidth: 1000, margin: '0 auto', padding: '24px 16px' }}>
            <SkateboardTabBar
                activeKey={activeTab}
                onChange={setActiveTab}
                items={tabItems}
            />
            <div style={{ marginTop: 16 }}>
                {renderTabContent()}
            </div>
        </div>
    );
}

// client-Vue3/src/pages/AdminPage.vue
<template>
	<div class="admin-page">
		<!-- 滑板标签栏切换 -->
		<SkateboardTabBar
			:active-key="activeTab"
			:items="tabItems"
			@update:active-key="activeTab = $event"
		/>

		<!-- 标签页内容 -->
		<div class="admin-tab-content">
			<AuditTab v-if="activeTab === 'audit'" />
			<UserTab v-if="activeTab === 'users'" />
			<TripTab v-if="activeTab === 'trips'" />
			<OperationLogTab v-if="activeTab === 'logs'" />
		</div>
	</div>
</template>

<script setup lang="ts">
	import { ref, onMounted } from "vue";
	import { useRouter } from "vue-router";
	import { useAuthStore } from "../stores/authStore";
	import AuditTab from "../components/admin/AuditTab.vue";
	import UserTab from "../components/admin/UserTab.vue";
	import TripTab from "../components/admin/TripTab.vue";
	import OperationLogTab from "../components/admin/OperationLogTab.vue";
	import SkateboardTabBar from "../components/SkateboardTabBar.vue";

	const router = useRouter();
	const authStore = useAuthStore();

	const activeTab = ref("audit");

	const tabItems = [
		{ key: "audit", label: "内容审核" },
		{ key: "users", label: "用户管理" },
		{ key: "trips", label: "旅程管理" },
		{ key: "logs", label: "操作日志" },
	];

	// 权限检查：仅管理员可访问
	onMounted(() => {
		if (!authStore.isAdmin) {
			router.replace("/");
		}
	});
</script>

<style scoped lang="scss">
	.admin-page {
		max-width: 1000px;
		margin: 0 auto;
		padding: 24px 16px;
	}

	.admin-tab-content {
		margin-top: 16px;
	}
</style>
