// client/src/pages/ExpenseFormPage.tsx
import React, { useState, useEffect } from 'react';
import {
  Form,
  Input,
  Button,
  DatePicker,
  Select,
  InputNumber,
  Typography,
  message,
  Card,
  Upload,
  Space,
  Image,
  Spin,
} from 'antd';
import { ArrowLeftOutlined, UploadOutlined, DeleteOutlined } from '@ant-design/icons';
import { useNavigate, useParams } from 'react-router-dom';
import * as expensesApi from '../api/expenses';
import { compressImage } from '../utils/compress';
import { EXPENSE_CATEGORIES } from '../types';
import type { Expense } from '../types';
import dayjs from 'dayjs';
import CurrencySwitcher from '../components/CurrencySwitcher';
import { useCurrencyStore } from '../store/currencyStore';

const { Title } = Typography;

interface TempFile {
  fileId: string;
  ext: string;
  previewUrl: string;
}

export default function ExpenseFormPage() {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(false);
  const [tempFiles, setTempFiles] = useState<TempFile[]>([]);
  const [uploading, setUploading] = useState(false);
  const [existingExpense, setExistingExpense] = useState<Expense | null>(null);
  const navigate = useNavigate();
  const { id, tripId, expenseId } = useParams<{ id?: string; tripId?: string; expenseId?: string }>();

  const resolvedTripId = id || tripId;
  const isEditing = !!expenseId;

  // 多币种支持
  const { currency, getCurrencySymbol, convertAmount } = useCurrencyStore();
  const currencySymbol = getCurrencySymbol();

  useEffect(() => {
    if (isEditing && expenseId) {
      setFetching(true);
      expensesApi.getExpenseById(expenseId)
        .then((expense) => {
          setExistingExpense(expense);
          form.setFieldsValue({
            category: expense.category,
            amount: Number(expense.amount),
            expenseDate: dayjs(expense.expenseDate),
            note: expense.note || '',
          });
        })
        .catch(() => {
          message.error('加载账单数据失败');
          navigate(-1);
        })
        .finally(() => setFetching(false));
    }
  }, [isEditing, expenseId, form, navigate]);

  const handleBeforeUpload = async (file: File) => {
    setUploading(true);
    try {
      const compressed = await compressImage(file, 750, 0.8);
      const compressedFile = new File([compressed], file.name.replace(/\.[^.]+$/, '.jpg'), { type: 'image/jpeg' });
      const result = await expensesApi.uploadFileToTemp(compressedFile);
      const previewUrl = URL.createObjectURL(compressedFile);
      setTempFiles((prev) => [...prev, { fileId: result.fileId, ext: result.ext, previewUrl }]);
      message.success('图片已暂存');
    } catch {
      message.error('图片上传失败');
    } finally {
      setUploading(false);
    }
    return false;
  };

  const handleRemoveReceipt = (index: number) => {
    setTempFiles((prev) => {
      const file = prev[index];
      if (file) {
        URL.revokeObjectURL(file.previewUrl);
      }
      return prev.filter((_, i) => i !== index);
    });
  };

  const onFinish = async (values: {
    category: string;
    amount: number;
    expenseDate: dayjs.Dayjs;
    note?: string;
  }) => {
    if (!resolvedTripId) return;
    setLoading(true);
    try {
      let receiptImages: string[] | null = null;

      if (tempFiles.length > 0) {
        const results = await expensesApi.persistMultiple(
          tempFiles.map((f) => ({ fileId: f.fileId, ext: f.ext }))
        );
        receiptImages = results.map((r) => r.imageUrl);
      } else if (isEditing && existingExpense?.receiptImages) {
        receiptImages = existingExpense.receiptImages;
      }

      const data: Record<string, unknown> = {
        category: values.category,
        amount: String(values.amount),
        expenseDate: values.expenseDate.format('YYYY-MM-DD HH:mm:ss'),
      };
      if (values.note) data.note = values.note;
      if (receiptImages) data.receiptImages = receiptImages;

      if (isEditing && expenseId) {
        await expensesApi.updateExpense(expenseId, data);
        message.success('账单更新成功');
        navigate(`/trip/${resolvedTripId}?tab=expenses`);
      } else {
        await expensesApi.createExpense(resolvedTripId, data);
        message.success('记账成功');
        navigate(`/trip/${resolvedTripId}?tab=expenses`);
      }
    } catch {
      message.error(isEditing ? '更新账单失败' : '记账失败');
    } finally {
      setLoading(false);
    }
  };

  if (fetching) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '50vh' }}>
        <Spin size="large" />
      </div>
    );
  }

  const existingImages = isEditing && existingExpense?.receiptImages ? existingExpense.receiptImages : [];
  const hasExistingImages = existingImages.length > 0;

  return (
    <Card style={{ maxWidth: 500, margin: '0 auto' }}>
      <Space style={{ marginBottom: 24, display: 'flex', justifyContent: 'space-between', width: '100%' }}>
        <Space>
          <Button
            icon={<ArrowLeftOutlined />}
            onClick={() => navigate(-1)}
            type="text"
          />
          <Title level={4} style={{ margin: 0 }}>
            {isEditing ? '编辑账单' : '记一笔'}
          </Title>
        </Space>
        <CurrencySwitcher />
      </Space>

      <Form
        form={form}
        layout="vertical"
        onFinish={onFinish}
        initialValues={{ category: '餐饮', expenseDate: dayjs() }}
      >
        <Form.Item
          name="category"
          label="分类"
          rules={[{ required: true, message: '请选择分类' }]}
        >
          <Select options={[...EXPENSE_CATEGORIES]} />
        </Form.Item>

        <Form.Item
          name="amount"
          label="金额"
          rules={[{ required: true, message: '请输入金额' }]}
        >
          <InputNumber
            min={0}
            precision={2}
            prefix={currencySymbol}
            style={{ width: '100%' }}
            placeholder="0.00"
          />
        </Form.Item>
        {/* 货币转换提示 */}
        <Form.Item noStyle shouldUpdate={(prev, cur) => prev.amount !== cur.amount}>
          {({ getFieldValue }) => {
            const amount = getFieldValue('amount');
            if (!amount || currency === 'CNY') return null;
            const converted = convertAmount(Number(amount));
            return (
              <div style={{ marginTop: -8, marginBottom: 16, fontSize: 12, color: '#888' }}>
                约 {currencySymbol}{converted.toFixed(currency === 'JPY' ? 0 : 2)}（按当前汇率自动转换）
              </div>
            );
          }}
        </Form.Item>

        <Form.Item
          name="expenseDate"
          label="消费日期"
          rules={[{ required: true, message: '请选择日期' }]}
        >
          <DatePicker
            showTime={{ format: 'HH:mm:ss' }}
            format="YYYY-MM-DD HH:mm:ss"
            style={{ width: '100%' }}
          />
        </Form.Item>

        <Form.Item name="note" label="备注">
          <Input.TextArea rows={3} placeholder="可选备注" />
        </Form.Item>

        <Form.Item label="小票照片">
          <Space direction="vertical" style={{ width: '100%' }}>
            {(hasExistingImages || tempFiles.length > 0) && (
              <Space wrap>
                {hasExistingImages && tempFiles.length === 0 && existingImages.map((img, idx) => (
                  <div key={`existing-${idx}`} style={{ position: 'relative', display: 'inline-block' }}>
                    <Image
                      src={img}
                      alt={`小票 ${idx + 1}`}
                      width={100}
                      height={100}
                      style={{ objectFit: 'cover', borderRadius: 4 }}
                    />
                  </div>
                ))}
                {tempFiles.map((file, idx) => (
                  <div key={`new-${idx}`} style={{ position: 'relative', display: 'inline-block' }}>
                    <Image
                      src={file.previewUrl}
                      alt={`小票 ${idx + 1}`}
                      width={100}
                      height={100}
                      style={{ objectFit: 'cover', borderRadius: 4 }}
                    />
                    <Button
                      icon={<DeleteOutlined />}
                      size="small"
                      danger
                      type="text"
                      style={{
                        position: 'absolute',
                        top: -8,
                        right: -8,
                        borderRadius: '50%',
                        background: '#fff',
                        boxShadow: '0 1px 4px rgba(0,0,0,0.15)',
                      }}
                      onClick={() => handleRemoveReceipt(idx)}
                    />
                  </div>
                ))}
              </Space>
            )}
            <Upload
              beforeUpload={handleBeforeUpload}
              accept="image/jpeg,image/png,image/webp"
              showUploadList={false}
            >
              <Button icon={<UploadOutlined />} loading={uploading}>
                {tempFiles.length > 0 || hasExistingImages ? '添加更多图片' : '上传小票'}
              </Button>
            </Upload>
          </Space>
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" loading={loading} block>
            {isEditing ? '更新账单' : '保存账单'}
          </Button>
        </Form.Item>
      </Form>
    </Card>
  );
}

// client-Vue3/src/pages/ExpenseFormPage.vue
<template>
	<div style="max-width: 500px; margin: 0 auto">
		<el-card v-loading="loading">
			<el-space style="margin-bottom: 24px; display: flex; justify-content: space-between; width: 100%">
				<el-space>
					<el-button
						text
						:icon="ArrowLeft"
						@click="router.back()"
					/>
					<h4 style="margin: 0">{{ isEditing ? "编辑账单" : "记一笔" }}</h4>
				</el-space>
				<CurrencySwitcher />
			</el-space>

			<el-form
				ref="formRef"
				:model="formData"
				:rules="rules"
				label-position="top"
				@submit.prevent="handleSubmit"
			>
				<el-form-item
					prop="category"
					label="分类"
				>
					<el-select
						v-model="formData.category"
						style="width: 100%"
					>
						<el-option
							v-for="cat in categories"
							:key="cat.value"
							:value="cat.value"
							:label="cat.label"
						/>
					</el-select>
				</el-form-item>

				<el-form-item
					prop="amount"
					:label="'金额 (' + currencyStore.currency + ')'"
				>
					<el-input
						v-model="formData.amountStr"
						:placeholder="'0.00'"
						style="width: 100%"
					/>
				</el-form-item>
				<!-- 货币转换提示 -->
				<div
					v-if="formData.amountStr && currencyStore.currency !== 'CNY'"
					style="margin-top: -8px; margin-bottom: 16px; font-size: 12px; color: #888"
				>
					约 {{ currencyStore.getCurrencySymbol()
					}}{{ currencyStore.convertAmount(Number(formData.amountStr)).toFixed(currencyStore.currency === "JPY" ? 0 : 2) }}（按当前汇率自动转换）
				</div>

				<el-form-item
					prop="expenseDate"
					label="消费日期"
				>
					<el-date-picker
						v-model="formData.expenseDate"
						type="datetime"
						placeholder="选择日期"
						style="width: 100%"
						format="YYYY-MM-DD HH:mm:ss"
						value-format="YYYY-MM-DD HH:mm:ss"
					/>
				</el-form-item>

				<el-form-item
					prop="note"
					label="备注"
				>
					<el-input
						v-model="formData.note"
						type="textarea"
						:rows="3"
						placeholder="可选备注"
					/>
				</el-form-item>

				<!-- 小票照片 -->
				<el-form-item label="小票照片">
					<el-space
						direction="vertical"
						style="width: 100%"
					>
						<el-space
							v-if="existingImages.length > 0 || tempFiles.length > 0"
							wrap
						>
							<div
								v-for="(img, idx) in existingImages"
								:key="'existing-' + idx"
								style="position: relative; display: inline-block"
							>
								<el-image
									:src="img"
									:alt="'小票 ' + (idx + 1)"
									style="width: 100px; height: 100px; object-fit: cover; border-radius: 4px"
								/>
							</div>
							<div
								v-for="(file, idx) in tempFiles"
								:key="'new-' + idx"
								style="position: relative; display: inline-block"
							>
								<el-image
									:src="file.previewUrl"
									:alt="'小票 ' + (idx + 1)"
									style="width: 100px; height: 100px; object-fit: cover; border-radius: 4px"
								/>
								<el-button
									:icon="Delete"
									size="small"
									type="danger"
									text
									style="position: absolute; top: -8px; right: -8px; border-radius: 50%; background: #fff; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.15)"
									@click="handleRemoveReceipt(idx)"
								/>
							</div>
						</el-space>
						<el-upload
							:before-upload="handleBeforeUpload"
							accept="image/jpeg,image/png,image/webp"
							:show-file-list="false"
						>
							<el-button
								:icon="Upload"
								:loading="uploading"
							>
								{{ tempFiles.length > 0 || existingImages.length > 0 ? "添加更多图片" : "上传小票" }}
							</el-button>
						</el-upload>
					</el-space>
				</el-form-item>

				<el-form-item>
					<el-button
						type="primary"
						:loading="submitting"
						native-type="submit"
						style="width: 100%"
					>
						{{ isEditing ? "更新账单" : "保存账单" }}
					</el-button>
				</el-form-item>
			</el-form>
		</el-card>
	</div>
</template>

<script setup lang="ts">
	import { ref, reactive, onMounted } from "vue";
	import { useRoute, useRouter } from "vue-router";
	import { ArrowLeft, Delete, Upload } from "@element-plus/icons-vue";
	import { ElMessage } from "element-plus";
	import type { FormInstance, FormRules } from "element-plus";
	import { createExpense, getExpenseById, updateExpense, uploadFileToTemp, persistMultiple } from "../api/expenses";
	import { compressImage } from "../utils/compress";
	import { useCurrencyStore } from "../stores/currencyStore";
	import CurrencySwitcher from "../components/CurrencySwitcher.vue";
	import type { Expense } from "../types";
	import dayjs from "dayjs";

	const route = useRoute();
	const router = useRouter();
	const currencyStore = useCurrencyStore();
	const formRef = ref<FormInstance>();
	const submitting = ref(false);
	const loading = ref(false);
	const uploading = ref(false);

	const tripId = route.params.tripId as string;
	const expenseId = route.params.expenseId as string | undefined;
	const isEditing = !!expenseId;

	interface TempFile {
		fileId: string;
		ext: string;
		previewUrl: string;
	}

	const tempFiles = ref<TempFile[]>([]);
	const existingImages = ref<string[]>([]);

	const categories = [
		{ value: "餐饮", label: "餐饮" },
		{ value: "交通", label: "交通" },
		{ value: "住宿", label: "住宿" },
		{ value: "门票", label: "门票" },
		{ value: "购物", label: "购物" },
		{ value: "其他", label: "其他" },
	];

	const formData = reactive({
		category: "餐饮",
		amountStr: "",
		amount: 0,
		expenseDate: dayjs().format("YYYY-MM-DD HH:mm:ss"),
		note: "",
	});

	const rules: FormRules = {
		category: [{ required: true, message: "请选择分类", trigger: "change" }],
		amountStr: [{ required: true, message: "请输入金额", trigger: "blur" }],
		expenseDate: [{ required: true, message: "请选择日期", trigger: "change" }],
	};

	async function handleBeforeUpload(file: File): Promise<boolean> {
		uploading.value = true;
		try {
			const compressed = await compressImage(file, 750, 0.8);
			const compressedFile = new File([compressed], file.name.replace(/\.[^.]+$/, ".jpg"), { type: "image/jpeg" });
			const result = await uploadFileToTemp(compressedFile);
			const previewUrl = URL.createObjectURL(compressedFile);
			tempFiles.value.push({ fileId: result.fileId, ext: result.ext, previewUrl });
			ElMessage.success("图片已暂存");
		} catch {
			ElMessage.error("图片上传失败");
		} finally {
			uploading.value = false;
		}
		return false;
	}

	function handleRemoveReceipt(index: number) {
		const file = tempFiles.value[index];
		if (file) {
			URL.revokeObjectURL(file.previewUrl);
		}
		tempFiles.value.splice(index, 1);
	}

	async function handleSubmit() {
		if (!formRef.value) return;
		const valid = await formRef.value.validate().catch(() => false);
		if (!valid) return;

		submitting.value = true;
		try {
			let receiptImages: string[] | null = null;

			if (tempFiles.value.length > 0) {
				const results = await persistMultiple(tempFiles.value.map((f) => ({ fileId: f.fileId, ext: f.ext })));
				receiptImages = results.map((r) => r.imageUrl);
			} else if (isEditing && existingImages.value.length > 0) {
				receiptImages = existingImages.value;
			}

			const payload: Record<string, unknown> = {
				category: formData.category,
				amount: String(formData.amountStr),
				expenseDate: formData.expenseDate,
			};
			if (formData.note) payload.note = formData.note;
			if (receiptImages) payload.receiptImages = receiptImages;

			if (isEditing && expenseId) {
				await updateExpense(expenseId, payload);
				ElMessage.success("账单更新成功");
				router.push(`/trip/${tripId}?tab=expenses`);
			} else {
				await createExpense(tripId, payload);
				ElMessage.success("记账成功");
				router.push(`/trip/${tripId}?tab=expenses`);
			}
		} catch (error: unknown) {
			const err = error as { response?: { data?: { message?: string } } };
			ElMessage.error(err?.response?.data?.message || "操作失败");
		} finally {
			submitting.value = false;
		}
	}

	onMounted(async () => {
		if (isEditing && expenseId) {
			loading.value = true;
			try {
				const expense = await getExpenseById(expenseId);
				formData.category = expense.category;
				formData.amountStr = String(expense.amount);
				formData.expenseDate = expense.expenseDate;
				formData.note = expense.note || "";
				if (expense.receiptImages) {
					existingImages.value = expense.receiptImages;
				}
			} catch {
				ElMessage.error("加载账单失败");
				router.back();
			} finally {
				loading.value = false;
			}
		}
	});
</script>
