// client/src/pages/ExplorePage.tsx
import React, { useState } from 'react';
import {
  Card,
  Typography,
  Pagination,
  Tag,
  Empty,
  Space,
} from 'antd';
import {
  EnvironmentOutlined,
  CalendarOutlined,
} from '@ant-design/icons';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import dayjs from 'dayjs';
import { getPublicTrips } from '../api/trips';
import { useAuthStore } from '../store/authStore';
import { CardListSkeleton } from '../components/Skeletons';
import type { Trip } from '../types';

const { Title, Text } = Typography;

export default function ExplorePage() {
  const [page, setPage] = useState(1);
  const pageSize = 9;
  const navigate = useNavigate();
  const currentUserId = useAuthStore((s) => s.user?.id);

  const { data, isLoading } = useQuery({
    queryKey: ['publicTrips', page],
    queryFn: () => getPublicTrips({ page, pageSize }),
  });

  const handleCardClick = (tripId: string) => {
    navigate(`/public-trip/${tripId}`);
  };

  return (
    <div>
      <Title level={3} style={{ marginBottom: 24 }}>
        微游记
      </Title>
      <Text type="secondary" style={{ display: 'block', marginBottom: 24 }}>
        发现其他旅行者的精彩分享
      </Text>

      {isLoading ? (
        <CardListSkeleton count={6} />
      ) : data && data.list.length > 0 ? (
        <>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
              gap: 16,
            }}
          >
            {data.list.map((trip: Trip) => (
              <Card
                key={trip.id}
                hoverable
                onClick={() => handleCardClick(trip.id)}
                cover={
                  trip.coverImage ? (
                    <div
                      style={{
                        height: 180,
                        overflow: 'hidden',
                        background: '#f0f2f5',
                      }}
                    >
                      <img
                        src={trip.coverImage}
                        alt={trip.title}
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'cover',
                        }}
                      />
                    </div>
                  ) : (
                    <div
                      style={{
                        height: 180,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        background: '#f0f2f5',
                      }}
                    >
                      <EnvironmentOutlined
                        style={{ fontSize: 48, color: '#bfbfbf' }}
                      />
                    </div>
                  )
                }
              >
                <Card.Meta
                  title={
                    <Space>
                      {trip.title}
                      {currentUserId && trip.userId === currentUserId && (
                        <Tag color="orange">我的</Tag>
                      )}
                    </Space>
                  }
                  description={
                    <div>
                      <Space
                        direction="vertical"
                        size={4}
                        style={{ width: '100%' }}
                      >
                        <Space>
                          <EnvironmentOutlined />
                          <Text type="secondary">{trip.destination}</Text>
                        </Space>
                        <Space>
                          <CalendarOutlined />
                          <Text type="secondary">
                            {dayjs(trip.startDate).format('YYYY-MM-DD HH:mm:ss')} -{' '}
                            {dayjs(trip.endDate).format('YYYY-MM-DD HH:mm:ss')}
                          </Text>
                        </Space>
                        <Space>
                          <Text type="secondary">
                            {trip.User?.username ? `@${trip.User.username}` : ''}
                          </Text>
                        </Space>
                        {trip.isEnded === 1 ? (
                          <Tag color="blue">已结束</Tag>
                        ) : (
                          <Tag color="green">进行中</Tag>
                        )}
                      </Space>
                    </div>
                  }
                />
              </Card>
            ))}
          </div>
          <div style={{ textAlign: 'center', marginTop: 24 }}>
            <Pagination
              current={page}
              total={data.total}
              pageSize={pageSize}
              onChange={setPage}
              showSizeChanger={false}
            />
          </div>
        </>
      ) : (
        <Empty description="暂无公开游记" />
      )}
    </div>
  );
}

// client-Vue3/src/pages/ExplorePage.vue
<template>
	<div>
		<h3 style="margin-bottom: 24px; font-size: 20px; font-weight: 600">微游记</h3>
		<span style="display: block; margin-bottom: 24px; color: rgba(0, 0, 0, 0.45); font-size: 14px"> 发现其他旅行者的精彩分享 </span>

		<CardListSkeleton
			v-if="loading"
			:count="6"
		/>

		<div
			v-else-if="trips.length > 0"
			style="display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 16px"
		>
			<el-card
				v-for="trip in trips"
				:key="trip.id"
				:body-style="{ padding: 0 }"
				style="cursor: pointer"
				shadow="hover"
				@click="navigateToTrip(trip)"
			>
				<el-image
					v-if="trip.coverImage"
					:src="trip.coverImage"
					style="width: 100%; height: 160px; object-fit: cover"
					fit="cover"
				/>
				<div
					v-else
					style="width: 100%; height: 160px; background: #f0f2f5; display: flex; align-items: center; justify-content: center"
				>
					<MyTripIcon
						:size="48"
						color="#bfbfbf"
					/>
				</div>
				<div style="padding: 12px 16px">
					<div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px">
						<h4 style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; word-break: break-word; margin: 0">
							{{ trip.title }}
						</h4>
						<el-tag
							v-if="currentUserId && trip.userId === currentUserId"
							type="warning"
							size="small"
							>我的</el-tag
						>
					</div>
					<div style="display: flex; flex-direction: column; gap: 4px; color: rgba(0, 0, 0, 0.45); font-size: 13px">
						<div>
							<el-icon style="margin-right: 4px"><Location /></el-icon>
							{{ trip.destination }}
						</div>
						<div>
							<el-icon style="margin-right: 4px"><Timer /></el-icon>
							{{ formatDate(trip.startDate) }} - {{ formatDate(trip.endDate) }}
						</div>
						<div>
							<el-icon style="margin-right: 4px"><User /></el-icon>
							{{ trip.User?.username || "匿名用户" }}
						</div>
						<div>
							<el-tag
								v-if="trip.isEnded"
								type="primary"
								size="small"
								>已结束</el-tag
							>
							<el-tag
								v-else
								type="success"
								size="small"
								>进行中</el-tag
							>
						</div>
					</div>
				</div>
			</el-card>
		</div>

		<el-empty
			v-else
			description="暂无公开游记"
		/>

		<el-pagination
			v-if="total > pageSize"
			v-model:current-page="currentPage"
			:total="total"
			:page-size="pageSize"
			layout="prev, pager, next"
			style="text-align: center; margin-top: 24px"
		/>
	</div>
</template>

<script setup lang="ts">
	import { ref, onMounted, watch } from "vue";
	import { useRouter } from "vue-router";
	import { User, Location, Timer } from "@element-plus/icons-vue";
	import { ElMessage } from "element-plus";
	import { getPublicTrips } from "../api/trips";
	import MyTripIcon from "../components/MyTripIcon.vue";
	import CardListSkeleton from "../components/CardListSkeleton.vue";
	import { useAuthStore } from "../stores/authStore";
	import type { Trip } from "../types";
	import dayjs from "dayjs";

	const router = useRouter();
	const authStore = useAuthStore();
	const trips = ref<Trip[]>([]);
	const loading = ref(true);
	const total = ref(0);
	const currentPage = ref(1);
	const pageSize = 9;

	const currentUserId = authStore.user?.id;

	function formatDate(dateStr: string) {
		return dayjs(dateStr).format("YYYY-MM-DD HH:mm:ss");
	}

	async function loadTrips() {
		loading.value = true;
		try {
			const data = await getPublicTrips({ page: currentPage.value, pageSize });
			trips.value = data.list;
			total.value = data.total;
		} catch {
			ElMessage.error("加载公开游记失败");
		} finally {
			loading.value = false;
		}
	}

	function navigateToTrip(trip: Trip) {
		router.push(`/explore/${trip.id}`);
	}

	watch(currentPage, () => {
		loadTrips();
	});

	onMounted(() => {
		loadTrips();
	});
</script>
