// client/src/pages/HomePage.tsx
import React, { useEffect, useState } from 'react';
import {
  Card,
  Row,
  Col,
  Typography,
  Button,
  Empty,
  Space,
  Tag,
  message,
  Popconfirm,
} from 'antd';
import {
  EditOutlined,
  DeleteOutlined,
  EnvironmentOutlined,
  CalendarOutlined,
  DollarOutlined,
  FileTextOutlined,
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import * as tripsApi from '../api/trips';
import { CardListSkeleton } from '../components/Skeletons';
import type { Trip } from '../types';
import dayjs from 'dayjs';

const { Title, Text } = Typography;

export default function HomePage() {
  const [trips, setTrips] = useState<Trip[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  const fetchTrips = async () => {
    setLoading(true);
    try {
      const result = await tripsApi.getTrips({ page: 1, pageSize: 50 });
      setTrips(result.list);
    } catch (err: unknown) {
      const error = err as { response?: { status?: number; data?: { message?: string } }; message?: string };
      if (error.response?.status === 401) {
        message.error('登录已过期，请重新登录');
      } else if (error.response?.status === 500) {
        message.error('服务器错误，请检查后端是否正常运行');
      } else if (error.message?.includes('Network Error')) {
        message.error('无法连接服务器，请确认后端已启动 (端口 3434)');
      } else {
        message.error(`加载旅程列表失败: ${error.response?.data?.message || error.message || '未知错误'}`);
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTrips();
  }, []);

  const handleDelete = async (id: string) => {
    try {
      await tripsApi.deleteTrip(id);
      message.success('旅程已删除');
      fetchTrips();
    } catch {
      message.error('删除失败');
    }
  };

  if (loading) {
    return <CardListSkeleton count={8} />;
  }

  return (
    <div>
      <Title level={3} style={{ marginBottom: 24 }}>
        我的旅程
      </Title>

      {trips.length === 0 ? (
        <Empty description="还没有旅程，点击上方按钮开始记录吧" />
      ) : (
        <Row gutter={[16, 16]}>
          {trips.map((trip) => (
            <Col key={trip.id} xs={24} sm={12} md={8} lg={6}>
              <Card
                hoverable
                onClick={() => navigate(`/trip/${trip.id}`)}
                cover={
                  trip.coverImage ? (
                    <img
                      alt={trip.title}
                      src={trip.coverImage}
                      style={{ height: 160, objectFit: 'cover' }}
                    />
                  ) : (
                    <div
                      style={{
                        height: 160,
                        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}
                    >
                      <EnvironmentOutlined
                        style={{ fontSize: 48, color: 'rgba(255,255,255,0.6)' }}
                      />
                    </div>
                  )
                }
                actions={[
                  <EditOutlined
                    key="edit"
                    onClick={(e) => {
                      e.stopPropagation();
                      navigate(`/trip/${trip.id}/edit`);
                    }}
                  />,
                  <Popconfirm
                    key="delete"
                    title="确定要删除这个旅程吗？所有账单和游记也会被删除。"
                    onConfirm={(e) => {
                      e?.stopPropagation();
                      handleDelete(trip.id);
                    }}
                    onCancel={(e) => e?.stopPropagation()}
                  >
                    <DeleteOutlined
                      onClick={(e) => e.stopPropagation()}
                      onMouseEnter={(e) => { e.currentTarget.style.color = '#ff7875'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.color = ''; }}
                    />
                  </Popconfirm>,
                ]}
              >
                <Card.Meta
                  title={
                    <Space>
                      {trip.isPublic === 1 && <Tag color="green">公开</Tag>}
                      {trip.title}
                      {trip.isEnded === 1 && <Tag color="blue">已结束</Tag>}
                    </Space>
                  }
                  description={
                    <Space direction="vertical" size={4}>
                      <Text>
                        <EnvironmentOutlined /> {trip.destination}
                      </Text>
                      <Text type="secondary">
                        <CalendarOutlined /> {dayjs(trip.startDate).format('YYYY-MM-DD HH:mm:ss')}{' '}
                        - {dayjs(trip.endDate).format('YYYY-MM-DD HH:mm:ss')}
                      </Text>
                      <Space>
                        <Text type="secondary">
                          <DollarOutlined /> {trip.expenseCount} 笔账单
                        </Text>
                        <Text type="secondary">
                          <FileTextOutlined /> {trip.noteCount} 篇游记
                        </Text>
                      </Space>
                    </Space>
                  }
                />
              </Card>
            </Col>
          ))}
        </Row>
      )}
    </div>
  );
}

// client-Vue3/src/pages/HomePage.vue
<template>
	<div>
		<h3 style="margin-bottom: 24px">我的旅程</h3>

		<CardListSkeleton
			v-if="loading"
			:count="8"
		/>

		<el-empty
			v-else-if="trips.length === 0"
			description="还没有旅程，点击上方按钮开始记录吧"
		/>

		<el-row
			v-else
			:gutter="16"
		>
			<el-col
				v-for="trip in trips"
				:key="trip.id"
				:xs="24"
				:sm="12"
				:md="8"
				:lg="6"
				style="margin-bottom: 16px"
			>
				<el-card
					:body-style="{ padding: 0 }"
					shadow="hover"
					style="cursor: pointer"
					@click="router.push(`/trip/${trip.id}`)"
				>
					<!-- 封面图 -->
					<el-image
						v-if="trip.coverImage"
						:src="trip.coverImage"
						style="width: 100%; height: 160px; object-fit: cover"
						fit="cover"
					/>
					<div
						v-else
						style="height: 160px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center"
					>
						<MyTripIcon
							:size="48"
							color="rgba(255,255,255,0.6)"
						/>
					</div>

					<!-- 卡片内容 -->
					<div style="padding: 16px 16px 12px">
						<div style="margin-bottom: 8px">
							<el-space :size="4">
								<el-tag
									v-if="trip.isPublic === 1"
									type="success"
									size="small"
									>公开</el-tag
								>
								<span style="font-weight: 600">{{ trip.title }}</span>
								<el-tag
									v-if="trip.isEnded === 1"
									type="primary"
									size="small"
									>已结束</el-tag
								>
							</el-space>
						</div>
						<div style="display: flex; flex-direction: column; gap: 4px; font-size: 13px; color: #666">
							<div>
								<el-icon style="margin-right: 4px"><Location /></el-icon>
								{{ trip.destination }}
							</div>
							<div style="color: #999">
								<el-icon style="margin-right: 4px"><Timer /></el-icon>
								{{ formatDate(trip.startDate) }} - {{ formatDate(trip.endDate) }}
							</div>
							<div style="display: flex; gap: 12px; color: #999">
								<span>
									<el-icon style="margin-right: 4px"><Money /></el-icon>
									{{ trip.expenseCount }} 笔账单
								</span>
								<span>
									<el-icon style="margin-right: 4px"><Document /></el-icon>
									{{ trip.noteCount }} 篇游记
								</span>
							</div>
						</div>
					</div>

					<!-- 操作按钮区域（底部，与 Ant Design Card actions 一致） -->
					<div style="display: flex; justify-content: flex-end; border-top: 1px solid #f0f0f0; padding: 0 12px; background: #fafafa">
						<el-button
							text
							:icon="Edit"
							size="small"
							@click.stop="router.push(`/trip/${trip.id}/edit`)"
						/>
						<el-popconfirm
							title="确定要删除这个旅程吗？所有账单和游记也会被删除。"
							@confirm="handleDelete(trip.id)"
						>
							<template #reference>
								<el-button
									text
									:icon="Delete"
									size="small"
									type="danger"
									@click.stop
									@mouseenter="
										(e: MouseEvent) => {
											(e.currentTarget as HTMLElement).style.color = '#ff7875';
										}
									"
									@mouseleave="
										(e: MouseEvent) => {
											(e.currentTarget as HTMLElement).style.color = '';
										}
									"
								/>
							</template>
						</el-popconfirm>
					</div>
				</el-card>
			</el-col>
		</el-row>

		<el-pagination
			v-if="total > pageSize"
			v-model:current-page="currentPage"
			:total="total"
			:page-size="pageSize"
			layout="prev, pager, next"
			style="text-align: center; margin-top: 16px"
			@current-change="handlePageChange"
		/>
	</div>
</template>

<script setup lang="ts">
	import { ref, onMounted } from "vue";
	import { useRouter } from "vue-router";
	import { Edit, Delete, Location, Timer, Money, Document } from "@element-plus/icons-vue";
	import { ElMessage } from "element-plus";
	import { getTrips, deleteTrip } from "../api/trips";
	import MyTripIcon from "../components/MyTripIcon.vue";
	import CardListSkeleton from "../components/CardListSkeleton.vue";
	import type { Trip } from "../types";
	import dayjs from "dayjs";

	const router = useRouter();
	const trips = ref<Trip[]>([]);
	const loading = ref(true);
	const total = ref(0);
	const currentPage = ref(1);
	const pageSize = 50;

	function formatDate(dateStr: string) {
		return dayjs(dateStr).format("YYYY-MM-DD HH:mm:ss");
	}

	async function loadTrips(page = 1) {
		loading.value = true;
		try {
			const data = await getTrips({ page, pageSize });
			trips.value = data.list;
			total.value = data.total;
		} catch {
			ElMessage.error("加载旅程失败");
		} finally {
			loading.value = false;
		}
	}

	async function handleDelete(id: string) {
		try {
			await deleteTrip(id);
			ElMessage.success("旅程已删除");
			loadTrips(currentPage.value);
		} catch {
			ElMessage.error("删除失败");
		}
	}

	function handlePageChange(page: number) {
		currentPage.value = page;
		loadTrips(page);
	}

	onMounted(() => {
		loadTrips();
	});
</script>
