// client/src/pages/RegisterPage.tsx
import bgLogin from '../assets/bg-login.jpg';

import React, { useState, useEffect, useCallback } from 'react';
import { Form, Input, Button, Card, Typography, message, Space } from 'antd';
import { MailOutlined, LockOutlined, UserOutlined, SafetyOutlined } from '@ant-design/icons';
import { Link, useNavigate } from 'react-router-dom';
import * as authApi from '../api/auth';
import { useAuthStore } from '../store/authStore';
import AppFooter from '../components/AppFooter';

const { Title, Text } = Typography;

export default function RegisterPage() {
  const [loading, setLoading] = useState(false);
  const [captchaSvg, setCaptchaSvg] = useState('');
  const [captchaId, setCaptchaId] = useState('');
  const navigate = useNavigate();
  const login = useAuthStore((s) => s.login);

  const fetchCaptcha = useCallback(async () => {
    try {
      const data = await authApi.getCaptcha();
      setCaptchaSvg(data.svg);
      setCaptchaId(data.captchaId);
    } catch {
      message.error('获取验证码失败');
    }
  }, []);

  useEffect(() => {
    fetchCaptcha();
  }, [fetchCaptcha]);

  const onFinish = async (values: {
    username: string;
    email: string;
    password: string;
    captchaText: string;
  }) => {
    setLoading(true);
    try {
      const result = await authApi.register({
        username: values.username,
        email: values.email,
        password: values.password,
        captchaId,
        captchaText: values.captchaText,
      });
      login(result.user, result.accessToken, result.refreshToken);
      message.success('注册成功');
      navigate('/');
    } catch (error: unknown) {
      const err = error as { response?: { data?: { message?: string } } };
      message.error(err?.response?.data?.message || '注册失败');
      fetchCaptcha();
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        background: `url(${bgLogin}) center/cover no-repeat`,
      }}
    >
      {/* 注册表单容器：flex-grow 撑开，内部 flex 居中 */}
      <div
        style={{
          flex: 1,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          padding: '24px 16px',
        }}
      >
        <Card style={{ width: 400, boxShadow: '0 8px 24px rgba(0,0,0,0.15)' }}>
          <Space direction="vertical" size="large" style={{ width: '100%' }}>
            <div style={{ textAlign: 'center' }}>
              <Title level={2} style={{ marginBottom: 4 }}>
                NomadNotes
              </Title>
              <Text type="secondary">游迹 - 创建你的账号</Text>
            </div>

            <Form layout="vertical" onFinish={onFinish} autoComplete="off">
              <Form.Item
                name="username"
                rules={[
                  { required: true, message: '请输入用户名' },
                  { min: 2, max: 50, message: '用户名长度需在 2-50 之间' },
                ]}
              >
                <Input
                  prefix={<UserOutlined />}
                  placeholder="用户名"
                  size="large"
                />
              </Form.Item>

              <Form.Item
                name="email"
                rules={[
                  { required: true, message: '请输入邮箱' },
                  { type: 'email', message: '邮箱格式不正确' },
                ]}
              >
                <Input prefix={<MailOutlined />} placeholder="邮箱" size="large" />
              </Form.Item>

              <Form.Item
                name="password"
                rules={[
                  { required: true, message: '请输入密码' },
                  { min: 6, message: '密码长度至少 6 位' },
                ]}
              >
                <Input.Password
                  prefix={<LockOutlined />}
                  placeholder="密码"
                  size="large"
                />
              </Form.Item>

              <Form.Item
                name="captchaText"
                rules={[{ required: true, message: '请输入验证码' }]}
              >
                <Space style={{ width: '100%' }}>
                  <Input
                    prefix={<SafetyOutlined />}
                    placeholder="验证码"
                    size="large"
                    style={{ width: '60%' }}
                  />
                  <div
                    style={{ width: '38%', cursor: 'pointer', height: 40 }}
                    onClick={fetchCaptcha}
                    dangerouslySetInnerHTML={{ __html: captchaSvg }}
                  />
                </Space>
              </Form.Item>

              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  loading={loading}
                  block
                  size="large"
                >
                  注册
                </Button>
              </Form.Item>
            </Form>

            <div style={{ textAlign: 'center' }}>
              <Text>
                已有账号？ <Link to="/login">立即登录</Link>
              </Text>
            </div>
          </Space>
        </Card>
      </div>

      {/* 页脚：ICP 备案信息 */}
      <AppFooter />
    </div>
  );
}

// client-Vue3/src/pages/RegisterPage.vue
<template>
	<div
		:style="{
			minHeight: '100vh',
			display: 'flex',
			flexDirection: 'column',
			backgroundImage: `url(${bgLogin})`,
			backgroundPosition: 'center',
			backgroundSize: 'cover',
			backgroundRepeat: 'no-repeat',
		}"
	>
		<!-- 注册表单容器：flex-grow 撑开，内部 flex 居中 -->
		<div
			:style="{
				flex: 1,
				display: 'flex',
				justifyContent: 'center',
				alignItems: 'center',
				padding: '24px 16px',
			}"
		>
			<el-card
				ref="formRef_gsap"
				style="width: 400px; box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15)"
			>
				<el-space
					direction="vertical"
					:size="24"
					style="width: 100%"
					alignment="center"
				>
					<div style="text-align: center">
						<h2
							class="login-page-title"
							style="margin: 0 0 4px 0; font-size: 30px; font-weight: 600; line-height: 1.35"
						>
							NomadNotes
						</h2>
						<div
							class="login-page-subtitle"
							style="color: rgba(0, 0, 0, 0.45); font-size: 14px; margin-bottom: 8px"
						>
							游迹 - 创建你的账号
						</div>
					</div>

					<el-form
						ref="formRef"
						:model="formData"
						:rules="rules"
						label-position="top"
						style="width: 100%"
						@submit.prevent="handleRegister"
					>
						<el-form-item prop="username">
							<el-input
								v-model="formData.username"
								:prefix-icon="User"
								placeholder="用户名"
								size="large"
							/>
						</el-form-item>

						<el-form-item prop="email">
							<el-input
								v-model="formData.email"
								:prefix-icon="Message"
								placeholder="邮箱"
								size="large"
							/>
						</el-form-item>

						<el-form-item prop="password">
							<el-input
								v-model="formData.password"
								:prefix-icon="Lock"
								type="password"
								placeholder="密码"
								size="large"
								show-password
							/>
						</el-form-item>

						<el-form-item prop="captchaText">
							<div style="display: flex; gap: 8px; width: 100%">
								<el-input
									v-model="formData.captchaText"
									:prefix-icon="Key"
									placeholder="验证码"
									size="large"
									style="width: 60%"
								/>
								<div
									style="width: 38%; cursor: pointer; height: 40px; flex-shrink: 0"
									@click="fetchCaptcha"
									v-html="captchaSvg"
								/>
							</div>
						</el-form-item>

						<el-form-item>
							<el-button
								type="primary"
								:loading="loading"
								native-type="submit"
								size="large"
								style="font-size: 16px; height: 40px; width: 100%"
							>
								注册
							</el-button>
						</el-form-item>
					</el-form>

					<div style="text-align: center">
						<el-link
							type="primary"
							@click="router.push('/login')"
						>
							已有账号？立即登录
						</el-link>
					</div>
				</el-space>
			</el-card>
		</div>

		<!-- 页脚：ICP 备案信息 -->
		<AppFooter />
	</div>
</template>

<script setup lang="ts">
	import { ref, reactive, onMounted } from "vue";
	import { Message, Lock, Key, User } from "@element-plus/icons-vue";
	import { useRouter } from "vue-router";
	import { ElMessage } from "element-plus";
	import type { FormInstance, FormRules } from "element-plus";
	import * as authApi from "../api/auth";
	import { useAuthStore } from "../stores/authStore";
	import bgLogin from "../assets/bg-login.jpg";
	import { useFadeIn } from "../composables/useGsapAnimations";
	import AppFooter from "../components/AppFooter.vue";

	const router = useRouter();
	const authStore = useAuthStore();
	const formRef = ref<FormInstance>();
	const loading = ref(false);
	const captchaSvg = ref("");

	// GSAP 动画
	const formRef_gsap = useFadeIn(0.2);
	const captchaId = ref("");

	const formData = reactive({
		username: "",
		email: "",
		password: "",
		captchaText: "",
	});

	const rules: FormRules = {
		username: [
			{ required: true, message: "请输入用户名", trigger: "blur" },
			{ min: 2, max: 50, message: "用户名长度需在 2-50 之间", trigger: "blur" },
		],
		email: [
			{ required: true, message: "请输入邮箱", trigger: "blur" },
			{ type: "email", message: "邮箱格式不正确", trigger: "blur" },
		],
		password: [
			{ required: true, message: "请输入密码", trigger: "blur" },
			{ min: 6, message: "密码长度至少 6 位", trigger: "blur" },
		],
		captchaText: [{ required: true, message: "请输入验证码", trigger: "blur" }],
	};

	async function fetchCaptcha() {
		try {
			const data = await authApi.getCaptcha();
			captchaSvg.value = data.svg;
			captchaId.value = data.captchaId;
		} catch {
			ElMessage.error("获取验证码失败");
		}
	}

	async function handleRegister() {
		if (!formRef.value) return;
		const valid = await formRef.value.validate().catch(() => false);
		if (!valid) return;

		loading.value = true;
		try {
			const result = await authApi.register({
				username: formData.username,
				email: formData.email,
				password: formData.password,
				captchaId: captchaId.value,
				captchaText: formData.captchaText,
			});
			authStore.login(result.user, result.accessToken, result.refreshToken);
			ElMessage.success("注册成功");
			router.push("/");
		} catch (error: unknown) {
			const err = error as { response?: { data?: { message?: string } } };
			ElMessage.error(err?.response?.data?.message || "注册失败");
			fetchCaptcha();
		} finally {
			loading.value = false;
		}
	}

	onMounted(() => {
		fetchCaptcha();
	});
</script>

<style scoped lang="scss">
	/* 暗黑主题支持 */
	.dark-theme .login-page-title {
		color: #e8e8e8 !important;
	}

	.dark-theme .login-page-subtitle {
		color: rgba(255, 255, 255, 0.45) !important;
	}
</style>
