// client-Vue3/src/components/admin/OperationLogTab.vue
<template>
	<div class="log-tab">
		<div class="tab-header">
			<h3>操作日志</h3>
			<el-select
				v-model="operationTypeFilter"
				size="small"
				placeholder="操作类型"
				clearable
				style="width: 140px"
				@change="handleFilterChange"
			>
				<el-option label="全部操作" value="" />
				<el-option label="禁用用户" value="user_disable" />
				<el-option label="启用用户" value="user_enable" />
				<el-option label="下架旅程" value="trip_takedown" />
				<el-option label="恢复旅程" value="trip_restore" />
				<el-option label="删除旅程" value="trip_delete" />
				<el-option label="删除游记" value="note_delete" />
			</el-select>
		</div>

		<div
			v-if="loading"
			class="loading-state"
		>
			<span>加载操作日志...</span>
		</div>

		<el-empty
			v-else-if="list.length === 0"
			description="暂无操作日志"
		/>

		<el-table
			v-else
			:data="list"
			stripe
			size="small"
			style="width: 100%"
		>
			<el-table-column
				label="操作人"
				width="100"
			>
				<template #default="{ row }">
					{{ row.adminName }}
				</template>
			</el-table-column>
			<el-table-column
				label="操作类型"
				width="100"
			>
				<template #default="{ row }">
					<el-tag
						size="small"
						:type="logTypeTag(row.operationType)"
					>
						{{ logTypeLabel(row.operationType) }}
					</el-tag>
				</template>
			</el-table-column>
			<el-table-column
				label="操作描述"
				min-width="300"
			>
				<template #default="{ row }">
					{{ row.description }}
				</template>
			</el-table-column>
			<el-table-column
				label="操作时间"
				width="160"
			>
				<template #default="{ row }">
					{{ formatTime(row.createdAt) }}
				</template>
			</el-table-column>
		</el-table>

		<div
			v-if="total > pageSize"
			class="log-pagination"
		>
			<el-pagination
				v-model:current-page="currentPage"
				:page-size="pageSize"
				:total="total"
				layout="prev, pager, next"
				@current-change="fetchLogs"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
	import { ref, onMounted } from "vue";
	import { ElMessage } from "element-plus";
	import {
		getOperationLogs,
		type AdminOperationLog,
	} from "../../api/admin";

	const list = ref<AdminOperationLog[]>([]);
	const loading = ref(false);
	const currentPage = ref(1);
	const total = ref(0);
	const pageSize = 20;
	const operationTypeFilter = ref("");

	function handleFilterChange() {
		currentPage.value = 1;
		fetchLogs();
	}

	async function fetchLogs() {
		loading.value = true;
		try {
			const res = await getOperationLogs({
				page: currentPage.value,
				pageSize,
				operationType: operationTypeFilter.value || undefined,
			});
			if (res.success) {
				list.value = res.data.list;
				total.value = res.data.total;
			}
		} catch {
			ElMessage.error("获取操作日志失败");
		} finally {
			loading.value = false;
		}
	}

	function logTypeTag(type: string) {
		const map: Record<string, "danger" | "success" | "warning" | "info"> = {
			user_disable: "danger",
			user_enable: "success",
			trip_takedown: "warning",
			trip_restore: "success",
			trip_delete: "danger",
			note_delete: "danger",
		};
		return map[type] || "info";
	}

	function logTypeLabel(type: string) {
		const map: Record<string, string> = {
			user_disable: "禁用用户",
			user_enable: "启用用户",
			trip_takedown: "下架旅程",
			trip_restore: "恢复旅程",
			trip_delete: "删除旅程",
			note_delete: "删除游记",
		};
		return map[type] || type;
	}

	function formatTime(dateStr: string) {
		if (!dateStr) return "";
		const d = new Date(dateStr);
		return d.toLocaleString("zh-CN", {
			year: "numeric",
			month: "2-digit",
			day: "2-digit",
			hour: "2-digit",
			minute: "2-digit",
		});
	}

	onMounted(() => {
		fetchLogs();
	});
</script>

<style scoped lang="scss">
	.log-tab {
		.tab-header {
			display: flex;
			align-items: center;
			justify-content: space-between;
			margin-bottom: 20px;

			h3 {
				margin: 0;
				font-size: 18px;
				font-weight: 600;
			}
		}

		.loading-state {
			text-align: center;
			padding: 60px 0;
			color: #999;
		}

		.log-pagination {
			display: flex;
			justify-content: center;
			margin-top: 24px;
		}
	}
</style>

// client/src/components/admin/OperationLogTab.tsx
import React, { useEffect, useState } from 'react';
import { Table, Tag, Empty, Select, message } from 'antd';
import { getOperationLogs, type AdminOperationLog } from '../../api/admin';

export default function OperationLogTab() {
    const [list, setList] = useState<AdminOperationLog[]>([]);
    const [loading, setLoading] = useState(false);
    const [currentPage, setCurrentPage] = useState(1);
    const [total, setTotal] = useState(0);
    const pageSize = 20;
    const [operationTypeFilter, setOperationTypeFilter] = useState<string | undefined>(undefined);

    const fetchLogs = async (page = currentPage) => {
        setLoading(true);
        try {
            const res = await getOperationLogs({
                page,
                pageSize,
                operationType: operationTypeFilter,
            });
            if (res.success) {
                setList(res.data.list);
                setTotal(res.data.total);
            }
        } catch {
            message.error('获取操作日志失败');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchLogs(1);
    }, [operationTypeFilter]);

    const logTypeConfig: Record<string, { color: string; label: string }> = {
        user_disable: { color: 'red', label: '禁用用户' },
        user_enable: { color: 'green', label: '启用用户' },
        trip_takedown: { color: 'orange', label: '下架旅程' },
        trip_restore: { color: 'green', label: '恢复旅程' },
        trip_delete: { color: 'red', label: '删除旅程' },
        note_delete: { color: 'red', label: '删除游记' },
    };

    const formatTime = (dateStr: string) => {
        if (!dateStr) return '';
        const d = new Date(dateStr);
        return d.toLocaleString('zh-CN', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    const columns = [
        {
            title: '操作人',
            dataIndex: 'adminName',
            key: 'adminName',
            width: 100,
        },
        {
            title: '操作类型',
            dataIndex: 'operationType',
            key: 'operationType',
            width: 100,
            render: (type: string) => {
                const config = logTypeConfig[type] || { color: 'default', label: type };
                return <Tag color={config.color}>{config.label}</Tag>;
            },
        },
        {
            title: '操作描述',
            dataIndex: 'description',
            key: 'description',
            minWidth: 300,
        },
        {
            title: '操作时间',
            dataIndex: 'createdAt',
            key: 'createdAt',
            width: 160,
            render: (val: string) => formatTime(val),
        },
    ];

    return (
        <div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
                <Select
                    placeholder="操作类型"
                    allowClear
                    style={{ width: 140 }}
                    value={operationTypeFilter}
                    onChange={(val) => setOperationTypeFilter(val)}
                    options={[
                        { label: '全部操作', value: undefined },
                        { label: '禁用用户', value: 'user_disable' },
                        { label: '启用用户', value: 'user_enable' },
                        { label: '下架旅程', value: 'trip_takedown' },
                        { label: '恢复旅程', value: 'trip_restore' },
                        { label: '删除旅程', value: 'trip_delete' },
                        { label: '删除游记', value: 'note_delete' },
                    ]}
                />
            </div>

            <Table
                dataSource={list}
                columns={columns}
                rowKey="id"
                loading={loading}
                size="small"
                pagination={{
                    current: currentPage,
                    pageSize,
                    total,
                    onChange: (page) => {
                        setCurrentPage(page);
                        fetchLogs(page);
                    },
                    showSizeChanger: false,
                }}
                locale={{ emptyText: <Empty description="暂无操作日志" /> }}
            />
        </div>
    );
}
