// client-Vue3/src/components/SkateboardNav.vue
<template>
  <div
    style="
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    "
  >
    <el-space>
      <el-button v-if="showBack" text @click="handleBack">
        <el-icon><ArrowLeft /></el-icon>返回
      </el-button>
      <span v-if="title" style="font-size: 18px; font-weight: 600">
        {{ title }}
      </span>
    </el-space>
    <slot name="extra" />
  </div>
</template>

<script setup lang="ts">
import { ArrowLeft } from "@element-plus/icons-vue";
import { useRouter } from "vue-router";

const props = withDefaults(
  defineProps<{
    title?: string;
    showBack?: boolean;
    backTo?: string;
  }>(),
  {
    showBack: true,
  },
);

const router = useRouter();

function handleBack() {
  if (props.backTo) {
    router.push(props.backTo);
  } else {
    router.back();
  }
}
</script>

// client/src/components/SkateboardNav.tsx
import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Button, Space } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';

/**
 * 通用导航组件，提供返回按钮和页面标题
 */
const SkateboardNav: React.FC<{
  title?: string;
  showBack?: boolean;
  backTo?: string;
  extra?: React.ReactNode;
}> = ({ title, showBack = true, backTo, extra }) => {
  const navigate = useNavigate();
  const location = useLocation();

  const handleBack = () => {
    if (backTo) {
      navigate(backTo);
    } else {
      navigate(-1);
    }
  };

  return (
    <div style={{ marginBottom: 16, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
      <Space>
        {showBack && (
          <Button icon={<ArrowLeftOutlined />} onClick={handleBack} type="text">
            返回
          </Button>
        )}
        {title && <span style={{ fontSize: 18, fontWeight: 600 }}>{title}</span>}
      </Space>
      {extra}
    </div>
  );
};

export default SkateboardNav;
